### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by iLeonidze** [ricmoo/nightminer#1]
Trying to run script from command line (Windows 8.1, Python 2.7.7) and catch:
```
C:\miner>python nightminer.py -a scrypt -o stratum+tcp://ltc.ghash.io:3333 -u up
100313695.worker1 -p password123
[2015-08-01 15:05:21] [INFO] Starting server on ltc.ghash.io:3333
[2015-08-01 15:05:22] [ERROR] ERROR: Python int too large to convert to C long
[2015-08-01 15:05:25] [ERROR] ERROR: Python int too large to convert to C long
[2015-08-01 15:05:26] [ERROR] ERROR: Python int too large to convert to C long
[2015-08-01 15:05:55] [ERROR] ERROR: Python int too large to convert to C long
Traceback (most recent call last):
File "nightminer.py", line 957, in <module>
miner.serve_forever()
File "nightminer.py", line 839, in serve_forever
time.sleep(10)
KeyboardInterrupt
```

With debug flag:
```
C:\miner>python nightminer.py -a scrypt -o stratum+tcp://ltc.ghash.io:3333 -u up
100313695.worker1 -p password123 -d
[2015-08-01 15:06:20] [DEBUG] TEST: Scrypt algorithm = 'pure python'
[2015-08-01 15:06:20] [DEBUG] TEST: Testing Subscription
[2015-08-01 15:06:20] [DEBUG] TEST: {u'result': [[u'mining.notify', u'ae6812eb4c
d7735a302a8a9dd95cf71f'], u'f800880e', 4], u'id': 1, u'error': None}
[2015-08-01 15:06:20] [DEBUG] TEST: {u'params': [32], u'id': None, u'method': u'
mining.set_difficulty'}
[2015-08-01 15:06:20] [DEBUG] TEST: {u'params': [u'1db7', u'0b29bfff96c5dc08ee65
e63d7b7bab431745b089ff0cf95b49a1631e1d2f9f31', u'0100000001000000000000000000000
0000000000000000000000000000000000000000000ffffffff2503777d07062f503253482f0405b
8c75208', u'0b2f436f696e48756e74722f0000000001603f352a010000001976a914c633315d37
6c20a973a758f7422d67f7bfed9c5888ac00000000', [u'f0dbca1ee1a9f6388d07d97c1ab0de0e
41acdf2edac4b95780ba0a1ec14103b3', u'8e43fd2988ac40c5d97702b7e5ccdf5b06d58f0e0d3
23f74dd5082232c1aedf7', u'1177601320ac928b8c145d771dae78a3901a089fa4aca8def01cbf
f747355818', u'9f64f3b0d9edddb14be6f71c3ac2e80455916e207ffc003316c6a515452aa7b4'
, u'2d0b54af60fad4ae59ec02031f661d026f2bb95e2eeb1e6657a35036c017c595'], u'000000
02', u'1b148272', u'52c7b81a', True], u'id': None, u'method': u'mining.notify'}
Traceback (most recent call last):
File "nightminer.py", line 942, in <module>
test_subscription()
File "nightminer.py", line 878, in test_subscription
for result in job.mine(nounce_start = 1210450368 - 3):
File "nightminer.py", line 434, in mine
for extranounce2 in xrange(0, 0xffffffff):
OverflowError: Python int too large to convert to C long
```

**Comment by ricmoo** [comment]
You are right! It works fine on my MacBook (64-bit), but on my raspberry pi (32-bit) I get the same error. You can change the number to 0x7fffffff for now to get up and running, and I'll push the change to master soon.

**Comment by iLeonidze** [comment]
Thanks, now it works fine on Windows 8.1 (x64, Python 2.7.10) and Ubuntu 15.04 (x64, Python 2.7.9)
