### ISSUE TITLE
Type Error and Syntax on Python2 and 3

### ISSUE THREAD

**Issue by NhlalukoG** [ricmoo/nightminer#11]
So the script actually executes on Py2 but

[2018-02-16 14:55:48] [INFO] Starting server on mcn.pool.minergate.com:45640
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "miner.py", line 648, in _handle_incoming_rpc
    output += '\n  ' + e.reply
TypeError: cannot concatenate 'str' and 'dict' objects

-----------------------------------------------------------------------------------------------------

Python3

  File "miner.py", line 327
    except Exception, e:
                                ^
SyntaxError: invalid syntax

**Comment by xeo1995** [comment]
replace output += '\n ' + e.reply
 by output += '\n ' + str(e.reply)
